language: go
sudo: false
go:
  - 1.14.x
install:
  - apk add --update bash git curl openssh-client ca-certificates git openssl-dev cmake make g++ openssl-libs-static
  - git config --global http.https://gopkg.in.followRedirects true
  - go mod tidy
script:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go test -race -v -cover $(go list ./... | grep -v /vendor/) -coverprofile=cartographer.coverage.out
  - cat *.coverage.out >> coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN